# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Owen Stranathan's Super Awesome Website! Yay!
logo: /images/signature_64.png

author: Owen Stranathan
favicon32: /images/favicon.png
favicon16: /images/favicon.png

reading: Game Engine Architecture
reading-link: https://www.gameenginebook.com/
studying: Unity
studying-link: https://unity3d.com/
learning: lots
learning-link: "#"

CV: /extras/CV.pdf

baseurl: "" # the subpath of your site, e.g. /blog
url: "owenstranathan.com" # the base hostname & protocol for your site, e.g. http://example.com

email: owenstranathan@gmail.com
github: https://github.com/owenstranathan
linkedin: owenstranathan
facebook: owen.stranathan.1
steam: OwenStranathan

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
