# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Owen Stranathan's Blog
logo: /images/signature_64.png

author: Owen Stranathan
avatar: /images/avatar.png
favicon32: /images/noodles32.png
favicon16: /images/noodles16.png

reading: '<a href="https://en.wikipedia.org/wiki/Zen_and_the_Art_of_Motorcycle_Maintenance">Zen and the Art of Motorcycle Maintenance</a>'
studying: '<a href="https://www.twoscoopspress.com/products/two-scoops-of-django-1-11">Two Scoops of Django 1.11</a>'
learning: '<a href="https://reactjs.org/docs">React.js</a>'

CV: /extras/CV.pdf

description: > # this means to ignore newlines until "baseurl:"
  I am a writer, programmer, musician and world traveler.
  I work hard to create beautiful works in my respective fields of interest.
  The primary purpose of this site is to host my CV and some writings.
  I write about my life and whatever I'm currently working on/interested in.
  You can follow me on some of my social media thingies.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

email: owenstranathan@gmail.com
github:  owenstranathan
linkedin: owenstranathan
facebook: owen.stranathan.1
steam: OwenStranathan

paginate: 4
paginate-path: "/blog/page:num/"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
