name: Owen's Blog
title: Owen's Blog
url: owenstranathan.com
linkedin: https://www.linkedin.com/in/owenstranathan/
github: https://github.com/owenstranathan/
email: owen@studiosodesign.com
markdown-extensions: # this can be used to enable markdown extensions site wide. See https://python-markdown.github.io/extensions/ for list of available extensions
 - "extra"
 - "toc"
#  - "codehilite"
markdown-extensions-configurations:
  codehilite:
    linenums: true
    css_class: highlight
copy-paths:
 - "css/"
 - "extra/"
 - "fonts/"
 - "img/"
 - "CNAME"
ignore-patterns:
 - "*.swp"
