name: Owen Stranathan's Blog
title: Owen Stranathan
description: Blog for my thoughts, observations, opinions, project, curiosities and anything and everything in between
# TODO (owen): Make it so blogger can have a local url that is injected when blogger serves the site locally
url: https://owenstranathan.com
linkedin: https://www.linkedin.com/in/owenstranathan/
github: https://github.com/owenstranathan/
CV_link: https://owenstranathan.com/extra/owenstranathanCV.pdf
email: owen@wabisoft.io
author: Owen Stranathan
markdown-extensions: # this can be used to enable markdown extensions site wide. See https://python-markdown.github.io/extensions/ for list of available extensions
 - "extra"
 - "toc"
#  - "codehilite"
markdown-extensions-configurations:
  codehilite:
    linenums: true
    css_class: highlight
copy-paths:
 - "css/"
 - "extra/"
 - "fonts/"
 - "img/"
 - "CNAME"
 - "js/"
ignore-patterns:
 - "*.swp"
